<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
    public function roomsWithUser(User $user)
    {
        $rooms = $this->createQueryBuilder('r')
            ->leftJoin('r.users', 'u')
            ->andWhere('u.id IN (:ids)')
            ->setParameter('ids', $user->getId())
            ->getQuery();

        return $rooms;
    }
}
